# Generated by Django 5.2.2 on 2025-08-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_labregistration_repeat_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='repeat_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
